steps:
- name: "gcr.io/cloud-builders/git"
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/demo-project-gcp/my-image', '.']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/demo-project-gcp/my-image']

